// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDiDSRhCC6pA2vjkJU4_30UWsPBwH5DWJs',
//     appId: '1:31777441329:web:20a1d0704fa5daaf47b710',
//     messagingSenderId: '31777441329',
//     projectId: 'edex-365',
//     authDomain: 'edex-365.firebaseapp.com',
//     storageBucket: 'edex-365.firebasestorage.app',
//     measurementId: 'G-16EQF0HMSN',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyApEYwgGlMlnhaGWKzJHQ4i0w_fwT7vBQk',
//     appId: '1:31777441329:android:96eba9980e1120e947b710',
//     messagingSenderId: '31777441329',
//     projectId: 'edex-365',
//     storageBucket: 'edex-365.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCsRjQVNTjyJjgJQDwQUkqfsLLFyqBWm5Y',
//     appId: '1:31777441329:ios:54c7948223d0e47747b710',
//     messagingSenderId: '31777441329',
//     projectId: 'edex-365',
//     storageBucket: 'edex-365.firebasestorage.app',
//     iosBundleId: 'com.example.edex365',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCsRjQVNTjyJjgJQDwQUkqfsLLFyqBWm5Y',
//     appId: '1:31777441329:ios:54c7948223d0e47747b710',
//     messagingSenderId: '31777441329',
//     projectId: 'edex-365',
//     storageBucket: 'edex-365.firebasestorage.app',
//     iosBundleId: 'com.example.edex365',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDiDSRhCC6pA2vjkJU4_30UWsPBwH5DWJs',
//     appId: '1:31777441329:web:90137445823b982b47b710',
//     messagingSenderId: '31777441329',
//     projectId: 'edex-365',
//     authDomain: 'edex-365.firebaseapp.com',
//     storageBucket: 'edex-365.firebasestorage.app',
//     measurementId: 'G-1HSQ6QDJ4M',
//   );
// }
